id: P000662
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC29
  title: ཚེ་བརྟན་ལྷ་རམས་པའི་གསུང་འབུམ།  ༼སྟོན་ཆ༽  ༼སྨད་ཆ༽
  author: ''
  volumes:
    d36aaf589a4543578919ff866beaa8be:
      image_group_id: I2PD17979
      title: ''
      volume_number: 1
      total_pages: 484
    ffa715b33e5a4db19c837f98119dc1e1:
      image_group_id: I2PD17980
      title: ''
      volume_number: 2
      total_pages: 406
