id: I805AF297
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:20:55+00:00'
last_modified: '2022-06-07T12:34:59.362255+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC29
  title: ཚེ་བརྟན་ལྷ་རམས་པའི་གསུང་འབུམ།  ༼སྟོན་ཆ༽  ༼སྨད་ཆ༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B882:
      image_group_id: I2PD17979
      title: ''
      total_pages: 484
      order: 1
      base_file: B882.txt
    '4716':
      image_group_id: I2PD17980
      title: ''
      total_pages: 406
      order: 2
      base_file: 4716.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
